public  class Flower {
  string a = 'smell';
    public static void wilt(string color){
        grow();
       /* account a = new account ();
        a.name =color ;
        insert a;*/
        
        system.debug('the colour is '+color);
        if(color == 'brown'){
            system.debug('wilted brown');
            system.debug('aa'); 
                }
        else if(color == 'red'){
            system.debug('wilted red');
        }
        else{
            system.debug('not wilted');
        }
        
    }
    
    
    public static void grow(){
        system.debug('it growing');
    }
    
    public  void sumOF1and2() {
        integer b;
        system.debug('3');
    }
   
}